### ISSUE TITLE
ERB Support

### ISSUE THREAD

**Issue by bartdorsey** [SublimeLinter/SublimeLinter-ruby#11]
It looks like you can do this to provide ERB file support

`erb -xT - <filename> | ruby -wc `

Any chance of getting this added?

**Comment by joshmfrankel** [comment]
This looks like it was discussed before in Issue #5. https://github.com/SublimeLinter/SublimeLinter-ruby/issues/5 Seems like what we will need is a new SublimeLinter-erb plugin.
