### ISSUE TITLE
How to silent undefined method errors?

### ISSUE THREAD

**Issue by j-jackson** [SublimeLinter/SublimeLinter-ruby#14]
Listing appears to be working correctly, however it lights up every method in a file as undefined if it has not been defined in the same file.

The example below highlights `protect_from_forgery` as undefined:
```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
```

<img width="589" alt="screen shot 2017-12-26 at 11 29 30 am" src="https://user-images.githubusercontent.com/22781082/34367316-5d5c4458-eafd-11e7-9e6b-73713872645c.png">

**Comment by braver** [comment]
This is a support question really and we don’t seem to have maintainers who use ruby a lot. Look for parameters or config options for the linter program itself, and otherwise SL has some filtering options built in.
