### ISSUE TITLE
"Aborting lint. SublimeLinter needs a restart of Sublime"

### ISSUE THREAD

**Issue by motine** [SublimeLinter/SublimeLinter-ruby#15]
I am using Sublime 3143, SublimeLinter 4.2.1 and SublimeLinter-ruby 1.0.17.
Each time I open a ruby file and type something the status bar says: "Aborting lint. SublimeLinter needs a restart of Sublime".

I have tried to add and remove the packages multiple times, but no luck.
I am aware, that this ticket does not contain sufficient information for debugging. Please let me know what else you need to reproduce the error.

**Comment by kaste** [comment]
We get that install/update event from Package Control and just show it in the status bar. You should open View > Console and look for what Package Control has to say.

Obviously removing and then re-adding the package just starts the install dance again. Just restarting should be the better choice.

**Comment by motine** [comment]
can you point me to the log?

**Comment by kaste** [comment]
Menu View > Show console

**Comment by motine** [comment]
alright. thanks. I will check it when I am back at my work station. thanks so far.

**Comment by kaste** [comment]
Closing due to age.
