### ISSUE TITLE
Latest commits/version mis-diagnose erb files

### ISSUE THREAD

**Issue by escapeit** [SublimeLinter/SublimeLinter-ruby#21]
Opened up sublime this morning and the .erb files are lit up. I see there's a shift from the (depreciated) `syntax` mappings to the `selector` and wonder if erb support was dropped inadvertently. Any thoughts?

<img width="835" alt="screenshot 2018-05-22 11 41 15" src="https://user-images.githubusercontent.com/4650555/40376919-386be1e6-5db5-11e8-8ae2-76706343a27f.png">
<img width="801" alt="screenshot 2018-05-22 11 41 25" src="https://user-images.githubusercontent.com/4650555/40376927-3c513c48-5db5-11e8-8685-dd8bbee86933.png">

**Comment by kaste** [comment]
Is the "correct" old behavior to ignore erbs or to lint them as whole files? 

Which base scope have erb files?

**Comment by escapeit** [comment]
Hi, I didn't consider the possibility that they were already being ignored. My expectations were that they would be linted as whole files akin to rb files. Incorrectly linting the file was not expected.

I'm not sure I follow your second question; I'm new to sublime dev. But the scope name within a ruby tag returns `text.html.ruby text.html.basic source.ruby.rails.embedded.html punctuation.section.embedded.ruby`

**Comment by kaste** [comment]
Can you just call 'ruby -wc some.erb'?

If we want to exclude them the selector should be changed to 'source.ruby - text.html.ruby', probably maybe.

**Comment by braver** [comment]
I found this via blame: https://github.com/SublimeLinter/SublimeLinter-ruby/commit/55a7c258851af3c495ab71b529f6d768096ff054 “removed erb support, doesn’t really work”.

So the correct approach would be to update the selector as @kase suggests.
