### ISSUE TITLE
No installed linter matches the view

### ISSUE THREAD

**Issue by maprihoda** [SublimeLinter/SublimeLinter-ruby#23]
With the debug option set to true:

```
SublimeLinter: sublime_linter.py:340  No installed linter matches the view
```

and the linter doesn't lint.

ruby 2.7.0p0
latest SublimeLinter

**Comment by kaste** [comment]
Well, make sure you installed this plugin (you also posted for rubocop, so you uninstalled or disabled that in between?), ensure it is enabled and you don't "exclude" the file you're currently viewing.

**Comment by maprihoda** [comment]
The plugin was installed and the viewed file wasn't excluded.

Looking at the plugin's source code, I can see:
```
'selector': 'source.ruby - text.html'
```

In the linter's settings, I put `source.rb` (all Ruby files in Rails have the `.rb` suffix) but no luck.

Is this plugin supposed to work only for `.ruby` files?

**Comment by kaste** [comment]
The file extension has nothing to do with the selector. Selector is a thing in editors which defines which syntax highlighter will be used, or is in fact in use.

With the default Sublime syntax/installation the default selector should just work. You can check by opening a file and hitting Ctrl+shift+alt+p

**Comment by maprihoda** [comment]
Interesting. Thanks for the explanation.

**Comment by maprihoda** [comment]
Having set both the `paths` and [`executable`](http://www.sublimelinter.com/en/latest/linter_settings.html#executable) (under the linter) settings caused the problem (`executable` alone didn't work).

For the record, it is enough to just list the path to the shims in the `paths`, like so:

```
      "paths": {
        "linux": [
          "/home/user/.rbenv/shims"
        ]
      },
```

works for both the Ruby and Rubocop linters.

**Comment by kaste** [comment]
Ah, okay. Setting paths is an escape hatch, it basically means the ENV within Sublime is not what you expect and have on the command line. You will have similar issues throughout Sublime, for example the built systems maybe won't just work.

There is a general solution for that although I don't remember it right now. You probably start Sublime by clicking on an icon or so, t.i. not from the command line. Just keep that in mind and maybe search or ask in the Sublime forum or Discourse chatter at some time.
